server:
  port: 8080
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/keycloak/**
        - id: movie
          uri: lb://msvc-movie
          predicates:
            - Path=/movies/**
        - id: music
          uri: lb://msvc-music
          predicates:
            - Path=/music/**
        - id: notebook
          uri: lb://msvc-notes
          predicates:
            - Path=/notebook/**
        - id: notes
          uri: lb://msvc-notes
          predicates:
            - Path=/note/**
        - id: phrase
          uri: lb://msvc-speaking
          predicates:
            - Path=/phrase/**
        - id: speaking
          uri: lb://msvc-speaking
          predicates:
            - Path=/speaking/**
        - id: topic
          uri: lb://msvc-speaking
          predicates:
            - Path=/topic/**
        - id: report
          uri: lb://msvc-report
          predicates:
            - Path=/report/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${JWT_RESOURCE_ID}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/


