server:
  port: 8095

spring:
  application:
    name: msvc-speaking
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  datasource:
    url: ${SPEAKING_DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${JWT_RESOURCE_ID}

eureka:
  instance:
    hostname: msvc-speaking
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka
